### ISSUE TITLE
dbConnect.php File

### ISSUE THREAD

**Issue by ferman2147** [orgrimd/n11.com-Restfull-API-Entegrasyon#1]
Hi, can you please share the code for dbConnect.php. Because I'm new to this API and I don't exactly know how it's concept works. It'd help big time if you could provide more info on this (database file). Thanks very much.
(Merhaba, lütfen dbConnect.php dosyasının kodlarını da paylaşabilir misiniz? Çünkü Bu API de yeniyim ve tam olarak konseptinin nasıl işlediğini bilmiyorum. Bununla ilgili (veritabanı dosyası) eksta bilgi paylaşabilirseniz çok faydası olur. Çok teşekkürler.

**Comment by orgrimd** [comment]
I can't share project source codes but i can help you for this. You can look any ezSql project or example DbConnection.php file. 

(projenin kodlarını paylaşamam ama bu konuda yardımcı olabilirim. Herhangi bir ezSql projesinin ya da örneğinin DbConnection.php dosyasını inceleyebilirsin.)

**Comment by ferman2147** [comment]
Thanks for the information. But can you explain why we would need a database connection if we can manipulate the data that we fetch directly from n11? I mean, the data is already stored there, what will we have in our own database, and how will we use it? (If you don't mind, I won't translate to Turkish this time :) )

**Comment by orgrimd** [comment]
Ok. no problem :) and yes you can fetch directly from n11. Well i can share an example connect.php

**Comment by ferman2147** [comment]
You know, I checked out ezSql, I'm fine with it. What I wonder is, what would I store in the database on my own side, like what kind of tables. From the code you have already shared, I see products, pictures, stocks, categories etc. I get the error "invalid arguments supplied for foreach()". If I just saw the code working, then I would understand what is what, and what does what. Sorry if I'm bothering, but it's my first serious touch to an api like this. :)

**Comment by orgrimd** [comment]
Hımm. I' m understanding to you and you are not bothering to me : ) no problem. This api a few complicate to understand if you first experiance similar api's. Sad but true. But i'll add an example query, let's return to code again.

**Comment by ferman2147** [comment]
I just checked the queries you added, I tried to do something similar before and I could send my response and get an error status from the server. That's something, right?! :) I will change my code and and database according to your query examples and try again. I will close the issue for now. I hope I don't need to reopen it.
